seed: 42

dataset:  
 train: artstract_splitted/train/
 valid: artstract_splitted/validation/
 test: artstract_splitted/test/
 
model:
  name: vgg 
  num_classes: 8

output: /home/nicolas/projects/mosaic/output/classifier_vgg

training:
  epochs: 100
  batch_size: 32
  lr: 0.0001