seed: 42

dataset:  
  train: artstract_balanced/train/
  valid: artstract_balanced/validation/
  test: artstract_balanced/test/
 
model:
  name: vgg 
  num_classes: 7

output: /home/nicolas/projects/mosaic/output/classifier_vgg

training:
  epochs: 100
  batch_size: 32
  lr: 0.0001