seed: 42

kge:
  kge_data: models/framester_conceptnet_kg.pickle 
  kge_weights: models/trans_e_128dim.pt

dataset:  
 train: artstract_splitted/train/
 valid: artstract_splitted/validation/
 test: artstract_splitted/test/
 
output: output/clip_infonce_early_stop.pt

encoding:
  name: vgg
  image_weights: models/finetuned_VGG_1000_epochs.pth
  use_classifier: false

training:
  epochs: 100
  batch_size: 32
  loss: infonce
  early_stop: true