seed: 42

kge:
  data: models/framester_conceptnet_kg.pickle 
  weights: models/trans_e_128dim.pt

dataset:  
  kg: Commonsense_MOSAIC/Common-sense_MOSAIC.ttl
  perception_json: Commonsense_MOSAIC/perception.json
  train: artstract_balanced/train/
  valid: artstract_balanced/validation/
  test: artstract_balanced/test/
 
encoder:
  name: vgg_artstract
  weights: output/classifier_vgg_artstract/model.ckpt
  
prediction:
  targets: comfort danger death fitness freedom power safety 

output: output/perception_vgg_artstract

training:
  epochs: 100
  batch_size: 32
  lr: 0.0001