seed: 42

kge:
  data: models/framester_conceptnet_kg.pickle 
  weights: models/trans_e_128dim.pt

dataset:  
  kg: Commonsense_MOSAIC/Common-sense_MOSAIC.ttl
  perception_json: Commonsense_MOSAIC/perception.json
  train: artstract_balanced/train/
  valid: artstract_balanced/validation/
  test: artstract_balanced/test/
 
encoder:
  name: vgg_artstract
  weights: /home/nicolas/projects/mosaic/output/classifier_vgg_artstract/model.ckpt
  
prediction:
  targets:
    - https://w3id.org/framester/conceptnet5/data/en/comfort
    - https://w3id.org/framester/conceptnet5/data/en/danger
    - https://w3id.org/framester/conceptnet5/data/en/death
    - https://w3id.org/framester/conceptnet5/data/en/fitness
    - https://w3id.org/framester/conceptnet5/data/en/freedom
    - https://w3id.org/framester/conceptnet5/data/en/power
    - https://w3id.org/framester/conceptnet5/data/en/safety 

output: output/perception_artstract

training:
  epochs: 100
  batch_size: 32
  lr: 0.001